# Generated by Django 2.1.3 on 2018-11-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
    ]
