# Generated by Django 2.1.3 on 2018-11-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info_app', '0002_remove_stock_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='indistry',
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
